sudo: required

language: ruby

services:
  - docker
  
before_script:
  - docker build -t ekt0s/dashing:candidate .

after_script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi
    
notifications:
  slack: sharmatools:5mPG2H1bvo4aKFXShoio63Ks